server:
  port: 8888
  servlet:
    context-path: /pmanager
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pmanager?characterEncoding=utf-8&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000

#用于mybatis
mybatis:
  mapper-locations: classpath:jp/db/mybatis/*/*.xml
  type-aliases-package: jp.db.mybatis.model

